# Generated by Django 5.1.3 on 2024-11-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=100)),
                ('waterbody', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('depth', models.FloatField(blank=True, null=True)),
                ('characteristic_name', models.CharField(max_length=100)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('result_unit', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.monitoringlocation')),
            ],
        ),
    ]
